# -*- coding: utf-8 -*-
"""Correlação_Notas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kz4d09L3jHwJ_L63FZoafZ_HdHnZh8p2
"""

import matplotlib.pyplot as plt

horas_estudadas= [2,3,4,5,6,7,8,9,10,11,12]
notas = [3,2.5,3,4,5,7,9,8.5,10,8,9.5]

plt.scatter (horas_estudadas, notas)

#Adicionando um retangulo com Rectangle para destacar a região de maior correlação
retangulo = plt.Rectangle((1,1),4,3,facecolor='red', alpha =0.2)
plt.gca().add_patch(retangulo)

#legenda do retangulo
plt.text(1,0.5,'Pior Performance',fontsize = 12, color= 'red')

plt.xlabel('Horas Estudadas')
plt.ylabel('Notas')
plt.title('Correlação entre Horas Estudadas e Notas')
plt.show()